### ISSUE TITLE
os install location and web panel sd card repair

### ISSUE THREAD

**Issue by kirksmacdonald1** [sicXnull/pantherx2_merryiot#1]
ok i have successfully installed this on an merryiot which is basically the panther x2

ok i just want to clear this up

is the os booted from the sd card with the ssh patch and not transfer d to the ram drive

i ask this as in the gui web panel it says sd not detected repair

so removed it and put a blank in as i did not want to loose my patch if i formated the card via gui

when i stuck the blank in the old firmware / os non patched version booted which was previously installed

i mention this as the built in disk space is only 20gb and will fill quickly with the block

is there any plans to make this ported over to the internal storage so we can format the sd card and use the storage card for space

as eventually the internall will run out of space

has anyone tried to format the sd card in the gui webpanel with the patch installed if so what was the result

im asking so i dont have to start from scratch if wipes the patch and i have to redo the flash as access to this miner is limited i dont want to keep going back and re flash to test things out

**Comment by sicXnull** [comment]
You can ignore the SD card errors for now. This system doesn't normally boot from SD card which is why you're getting that error. 

Also, 20GB is enough. Helium no longer stores the blockchain on disk, so disk usage will remain low.

**Comment by sicXnull** [comment]
Closing this. let me know if you have any questions.

**Comment by alkarout** [comment]
لايمكنني الوصل الى لوحة القيادة عن طريق ıp ولايمكنني تثبيت الموقع بعد تنزيل البرنامج الثابت هذا الرجو المساعدة

**Comment by alkarout** [comment]
I cannot connect to the dashboard via ıp and I cannot install the site after downloading this firmware. Please help
